resolver: lts-10.2

packages:
  - .
  - ../numhask
  - ../numhask-prelude

extra-deps:
  - diagrams-graphviz-1.4
  - protolude-0.2.2
  #- git: https://github.com/diagrams/diagrams-lib
  #  commit: fad4346e792d6cc089a8116f08cf48d8028ee813
  # - diagrams-lib-1.4.2
  #- git: https://github.com/tonyday567/graphviz
  #  commit: fb99187b3015a94551ad928451016391ff1a5465
  # - graphviz-2999.19.0.0
  #- protolude-0.2.1
  #- active-0.2.0.13
  # - diagrams-core-1.4.0.1
  #- diagrams-solve-0.1.1
  #- dual-tree-0.2.1
  #- fsnotify-0.2.1.1
  # - svg-builder-0.1.0.2
  # - wl-pprint-text-1.1.1.0
  #- git: https://github.com/tonyday567/wl-pprint-text
  #  commit: b172886271ca29e16ec47fcdc993c0956f384d32
  #- groups-0.4.1.0
  #- git: https://github.com/diagrams/monoid-extras
  #  commit: 1df9682752dac8c67392d2e80bb09cb7073f3d0b
  #- git: https://github.com/diagrams/diagrams-svg
  #  commit: 90bb22f0b97dee448ae552ed09d0786c8b564f18
  #- git: https://github.com/diagrams/svg-builder
  #  commit: 5bd888d3a9a44ae1afc0f4c85075b6579052aafd
  #- git: https://github.com/diagrams/diagrams-core
  #  commit: 9167044d561c91deec13d31c66714da8a1e00008

allow-newer: true
